import { useState, useContext, useEffect, useRef } from "react";
import styles from "./QRGenerator.module.css";
import { ThemeContext } from "../context/ThemeContext";
import { Link } from "react-router-dom";
import AdUnit from "../components/AdUnit";
import { QrCode, Download, AlertCircle, CheckCircle, Loader, Globe, Wifi, UserRound, Package, Smartphone, Target, Palette, Lock, Link2, FileText } from "lucide-react";

function QRGenerator() {
  const { darkMode } = useContext(ThemeContext);

  // Tabs: 'url', 'text', 'wifi', 'contact'
  const [activeTab, setActiveTab] = useState("url");

  // Inputs
  const [urlInput, setUrlInput] = useState("");
  const [textInput, setTextInput] = useState("");
  const [wifiSsid, setWifiSsid] = useState("");
  const [wifiPass, setWifiPass] = useState("");
  const [wifiSec, setWifiSec] = useState("WPA");
  const [cFirst, setCFirst] = useState("");
  const [cLast, setCLast] = useState("");
  const [cPhone, setCPhone] = useState("");
  const [cEmail, setCEmail] = useState("");

  // Common Settings
  const [qrSize, setQrSize] = useState(220);
  const [fgColor, setFgColor] = useState("#000000");
  const [bgColor, setBgColor] = useState("#ffffff");

  // Output
  const [qrCodeUrl, setQrCodeUrl] = useState(""); // Holds PNG data URL
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  // Debounce ref for auto-generation
  const autoGenTimeout = useRef(null);

  // Derive content string to be sent
  const deriveContent = () => {
    switch (activeTab) {
      case "url":
        return urlInput.trim();
      case "text":
        return textInput.trim();
      case "wifi":
        return wifiSsid ? `WIFI:T:${wifiSec};S:${wifiSsid};P:${wifiPass};;` : '';
      case "contact":
        return (cFirst || cLast) ? `BEGIN:VCARD\nVERSION:3.0\nN:${cLast};${cFirst}\nFN:${cFirst} ${cLast}\nTEL:${cPhone}\nEMAIL:${cEmail}\nEND:VCARD` : '';
      default:
        return '';
    }
  };

  const generateQR = async () => {
    const textToEncode = deriveContent();

    if (!textToEncode) {
      setQrCodeUrl(""); // Only clear when completely empty
      return;
    }

    setLoading(true);
    setError("");

    try {
      // NOTE: We're doing server-side generation via the API endpoint
      const response = await fetch(`${import.meta.env.VITE_API_BASE_URL}/qr-code`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          text: textToEncode,
          size: qrSize,
          fgColor,
          bgColor,
        }),
      });

      if (!response.ok) {
        throw new Error(`Server error: ${response.status}`);
      }

      const data = await response.json();
      setQrCodeUrl(data.qrDataUrl);
      setSuccess("Generated successfully!");
      setTimeout(() => setSuccess(""), 2000);
    } catch (err) {
      console.error("QR generation error:", err);
      // Don't show confusing error on partial typing to user
      if (err.message !== "Failed to fetch") {
        setError("Failed to generate QR code");
      }
    } finally {
      setLoading(false);
    }
  };

  // Auto Generate logic
  const handleInput = () => {
    if (autoGenTimeout.current) clearTimeout(autoGenTimeout.current);
    autoGenTimeout.current = setTimeout(() => {
      generateQR();
    }, 400); // 400ms debounce map
  };

  useEffect(() => {
    // Attempt generation if settings change
    handleInput();
  }, [qrSize, fgColor, bgColor, activeTab]);

  const downloadFile = async (format) => {
    if (!qrCodeUrl) return;

    // Default format generated by API is likely PNG 
    // SVG would need a separate API route or canvas tricks.
    // For now we will download PNG.
    const a = document.createElement("a");
    a.href = qrCodeUrl;
    a.download = `qrcode-pixelmind.${format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="page-wrap">
      {/* 1. HERO */}
      <div className={styles.toolHero}>
        <div className={styles.breadcrumb}>
          <Link to="/">Home</Link><span>›</span>
          <a href="#tools">Tools</a><span>›</span>
          <span style={{ color: "var(--text-soft)" }}>QR Code Generator</span>
        </div>
        <h1 className={styles.heroH1}>QR Code <em>Generator</em></h1>
        <p className={styles.heroP}>Generate custom QR codes for URLs, plain text, WiFi credentials, and contact cards. Customize colors and download as PNG — completely free.</p>
        <div className={styles.badges}>
          <div className={styles.badge}><Palette size={12} strokeWidth={2} /> Custom Colors</div>
          <div className={styles.badge}><Download size={12} strokeWidth={2} /> Download PNG</div>
          <div className={styles.badge}><Lock size={12} strokeWidth={2} /> Private</div>
        </div>
      </div>

      <div className="ad-row">
        <AdUnit format="728x90" label="Advertisement · Leaderboard" />
      </div>

      {/* 2. MAIN TOOL */}
      <div className={styles.qrMain}>

        {/* LEFT COLUMN: FORM */}
        <div>
          <div className={styles.typeTabs}>
            <button className={`${styles.typeTab} ${activeTab === 'url' ? styles.active : ''}`} onClick={() => setActiveTab('url')}><Link2 size={13} /> URL</button>
            <button className={`${styles.typeTab} ${activeTab === 'text' ? styles.active : ''}`} onClick={() => setActiveTab('text')}><FileText size={13} /> Text</button>
            <button className={`${styles.typeTab} ${activeTab === 'wifi' ? styles.active : ''}`} onClick={() => setActiveTab('wifi')}><Wifi size={13} /> WiFi</button>
            <button className={`${styles.typeTab} ${activeTab === 'contact' ? styles.active : ''}`} onClick={() => setActiveTab('contact')}><UserRound size={13} /> Contact</button>
          </div>

          <div className={styles.qrForm}>

            {activeTab === 'url' && (
              <div className={styles.sGroup}>
                <div className={styles.sLabel}>Enter URL</div>
                <input
                  type="url"
                  className={styles.sInput}
                  value={urlInput}
                  onChange={(e) => { setUrlInput(e.target.value); handleInput(); }}
                  placeholder="https://example.com"
                />
              </div>
            )}

            {activeTab === 'text' && (
              <div className={styles.sGroup}>
                <div className={styles.sLabel}>Enter Text</div>
                <textarea
                  className={styles.sTextarea}
                  value={textInput}
                  onChange={(e) => { setTextInput(e.target.value); handleInput(); }}
                  placeholder="Enter any text..."
                />
              </div>
            )}

            {activeTab === 'wifi' && (
              <>
                <div className={styles.sGroup}>
                  <div className={styles.sLabel}>Network Name (SSID)</div>
                  <input type="text" className={styles.sInput} value={wifiSsid} onChange={(e) => { setWifiSsid(e.target.value); handleInput(); }} placeholder="MyHomeNetwork" />
                </div>
                <div className={styles.sGroup}>
                  <div className={styles.sLabel}>Password</div>
                  <input type="password" className={styles.sInput} value={wifiPass} onChange={(e) => { setWifiPass(e.target.value); handleInput(); }} placeholder="••••••••" />
                </div>
                <div className={styles.sGroup}>
                  <div className={styles.sLabel}>Security Type</div>
                  <select className={styles.sInput} value={wifiSec} onChange={(e) => { setWifiSec(e.target.value); handleInput(); }}>
                    <option value="WPA">WPA/WPA2</option>
                    <option value="WEP">WEP</option>
                    <option value="">None</option>
                  </select>
                </div>
              </>
            )}

            {activeTab === 'contact' && (
              <>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                  <div className={styles.sGroup}>
                    <div className={styles.sLabel}>First Name</div>
                    <input type="text" className={styles.sInput} value={cFirst} onChange={(e) => { setCFirst(e.target.value); handleInput(); }} placeholder="Ali" />
                  </div>
                  <div className={styles.sGroup}>
                    <div className={styles.sLabel}>Last Name</div>
                    <input type="text" className={styles.sInput} value={cLast} onChange={(e) => { setCLast(e.target.value); handleInput(); }} placeholder="Khan" />
                  </div>
                </div>
                <div className={styles.sGroup}>
                  <div className={styles.sLabel}>Phone</div>
                  <input type="tel" className={styles.sInput} value={cPhone} onChange={(e) => { setCPhone(e.target.value); handleInput(); }} placeholder="+92 300 1234567" />
                </div>
                <div className={styles.sGroup}>
                  <div className={styles.sLabel}>Email</div>
                  <input type="email" className={styles.sInput} value={cEmail} onChange={(e) => { setCEmail(e.target.value); handleInput(); }} placeholder="ali@example.com" />
                </div>
              </>
            )}

            <button className={styles.genBtn} onClick={generateQR} disabled={loading || !deriveContent()}>
              {loading ? <><Loader size={18} className="spinner" /> Generating...</> : "Generate QR Code →"}
            </button>

            {error && (
              <div className={`${styles.alertMsg} ${styles.alertError}`}>
                <AlertCircle size={14} /> {error}
              </div>
            )}
            {success && (
              <div className={`${styles.alertMsg} ${styles.alertSuccess}`}>
                <CheckCircle size={14} /> {success}
              </div>
            )}

          </div>
        </div>

        {/* RIGHT COLUMN: PREVIEW + CUSTOMIZE */}
        <div className={styles.qrPreview}>
          <div className={styles.qrDisplay}>
            <div className={`${styles.qrCanvasWrap} ${qrCodeUrl ? styles.hasQr : ''}`}>
              {!qrCodeUrl ? (
                <div className={styles.qrPlaceholder}>
                  <span>▦</span>
                  <div>QR code will<br />appear here</div>
                </div>
              ) : (
                <img src={qrCodeUrl} alt="Generated QR" style={{ width: '100%', height: '100%', display: 'block' }} />
              )}
            </div>
            <div className={styles.qrActions}>
              <button
                className={`${styles.dlBtn} ${styles.dlPng}`}
                disabled={!qrCodeUrl}
                onClick={() => downloadFile('png')}
              >
                ⬇ PNG
              </button>
              {/* Optional SVG button disabled/hidden since backend sends PNG dataUrl usually 
                  If backend is updated to send svg, we can uncomment. 
                 <button className={`${styles.dlBtn} ${styles.dlSvg}`} disabled={!qrCodeUrl} onClick={() => downloadFile('svg')}>⬇ SVG</button>
              */}
            </div>
          </div>

          <div className={styles.customizePanel}>
            <div className={styles.custTitle}><Palette size={15} strokeWidth={1.8} /> Customize</div>
            <div className={styles.colorRow}>
              <div className={styles.colorGroup}>
                <div className={styles.colorLabel}>QR Color</div>
                <div className={styles.colorInputWrap}>
                  <input type="color" className={styles.colorSwatch} value={fgColor} onChange={(e) => setFgColor(e.target.value)} />
                  <span className={styles.colorHex}>{fgColor}</span>
                </div>
              </div>
              <div className={styles.colorGroup}>
                <div className={styles.colorLabel}>Background</div>
                <div className={styles.colorInputWrap}>
                  <input type="color" className={styles.colorSwatch} value={bgColor} onChange={(e) => setBgColor(e.target.value)} />
                  <span className={styles.colorHex}>{bgColor}</span>
                </div>
              </div>
            </div>

            <div className={styles.sGroup} style={{ marginTop: '8px' }}>
              <div className={styles.sLabel}>Size — <span>{qrSize}px</span></div>
              <div className={styles.sizeRow}>
                <input
                  type="range"
                  className={styles.rangeInput}
                  min="100"
                  max="600"
                  value={qrSize}
                  onChange={(e) => setQrSize(parseInt(e.target.value))}
                />
                <span className={styles.rangeVal}>{qrSize}px</span>
              </div>
            </div>
          </div>
        </div>

      </div>

      <div className="ad-row">
        <AdUnit format="728x90" label="Advertisement · Leaderboard" />
      </div>

      {/* 4. USE CASES */}
      <div className={styles.usesSec}>
        <div className="sec-label">Use Cases</div>
        <h2 className="sec-title">Where to use your <span className="ac">QR code</span></h2>
        <div className={styles.usesGrid}>
          <div className={styles.useCard}>
            <div className={styles.useIcon}><Globe size={22} strokeWidth={1.7} /></div>
            <div className={styles.useTitle}>Website Links</div>
            <div className={styles.useTxt}>Share your website on business cards, flyers, or posters without typing long URLs.</div>
          </div>
          <div className={styles.useCard}>
            <div className={styles.useIcon}><Wifi size={22} strokeWidth={1.7} /></div>
            <div className={styles.useTitle}>WiFi Access</div>
            <div className={styles.useTxt}>Let guests connect to your WiFi instantly — no need to share the password verbally.</div>
          </div>
          <div className={styles.useCard}>
            <div className={styles.useIcon}><UserRound size={22} strokeWidth={1.7} /></div>
            <div className={styles.useTitle}>Digital Business Cards</div>
            <div className={styles.useTxt}>Share your contact info with a quick scan. Perfect for networking events.</div>
          </div>
          <div className={styles.useCard}>
            <div className={styles.useIcon}><Package size={22} strokeWidth={1.7} /></div>
            <div className={styles.useTitle}>Product Packaging</div>
            <div className={styles.useTxt}>Link to product manuals, warranties, or how-to videos directly from packaging.</div>
          </div>
          <div className={styles.useCard}>
            <div className={styles.useIcon}><Smartphone size={22} strokeWidth={1.7} /></div>
            <div className={styles.useTitle}>Social Media</div>
            <div className={styles.useTxt}>Drive followers to your Instagram, YouTube, or TikTok profile with a single scan.</div>
          </div>
          <div className={styles.useCard}>
            <div className={styles.useIcon}><Target size={22} strokeWidth={1.7} /></div>
            <div className={styles.useTitle}>Marketing Campaigns</div>
            <div className={styles.useTxt}>Track campaign performance by linking QR codes to unique landing pages.</div>
          </div>
        </div>
      </div>

    </div>
  );
}

export default QRGenerator;
